CREATE OR REPLACE TRIGGER triggerupdate
AFTER UPDATE ON COULIBALY.NA_FOURNISSEURS
FOR EACH ROW
BEGIN
 --DBMS_OUTPUT.PUT_LINE('Modification en cascade de : ' ||:OLD.NOFOUR);
 --update COULIBALY.NA_PRODUITS set NOFOUR='' where NOFOUR=:OLD.NOFOUR;
 --INSERT INTO Fournisseur SELECT * FROM  COULIBALY.NA_PRODUITS WHERE NOFOUR=:OLD.NOFOUR;
--SELECT NOFOUR,NOMFOUR,NO,RUE,VILLE,CODEPOSTAL,TELEPHONE FROM COULIBALY.NA_FOURNISSEURS WHERE NOFOUR=:OLD.NOFOUR
UPDATE COULIBALY.NA_PRODUITS SET NOFOUR=:NEW.NOFOUR WHERE NOFOUR=:OLD.NOFOUR;
END;
/
PAUSE "Appuyez sur une touche pour continuer..."
@C:\Users\Nana\ProjetMABD\Sous_Menu_3.sql


